stages: 
  - build
  - test
  - deploy

build-job: 
  stage: build
  script: 
    - echo "building if nessitary"
    - npm build 

test-job: 
  stage: test
  script:
  - ./accessabilitify-testing.sh test.html

deploy-job: 
  stage: deploy
  script: 
    - echo "staging to deploy"