stages: 
  - test


#build-job: 
#  stage: build
#  image: node:latest
#  script: 
#    - echo "building if nessitary"
#    - npm build 

test-job: 
  stage: test
  image: docker:stable
  #services: docker:19.03.5-dind
  script:
  - docker build -t pa11y:$CI_PIPELINE_ID . 
  - ./test-script.sh nrk.no #needs to be changed to the expected outcome of the build thing


deploy-job: 
  stage: deploy
  script: 
    - echo "staging to deploy"
    - echo "this needs to be in another repo"