stages: 
  - build
  - test
  - deploy

build-job: 
  stage: build
  image: node:latest
  script: 
    - echo "building if nessitary"
    - npm build 

test-job: 
  stage: test
  image: docker:stable
  services: docker:19.03.5-dind
  script:
  - ./accessabilitify-testing.sh oslomet.no #needs to be changed to the expected outcome of the build thing
  artifacts: 
    paths:
      - 

deploy-job: 
  stage: deploy
  script: 
    - echo "staging to deploy"
